### ISSUE TITLE
STS22/LivedoorNewsClustering: Empty texts

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#1043]
STS22 & LivedoorNewsClustering contain empty samples. For some models this is fine, but other models (e.g. GritLM) will produce NaN embeddings in that case. I'm not sure what is the best solution - should we expect models to be able to embed empty texts or not (& remove them from these ds)?

**Comment by KennethEnevoldsen** [comment]
We should probably remove them - A more general fix is proposed in #1049

**Comment by KennethEnevoldsen** [comment]
I have proposed a fix for this in #1055. However, since this changes the score we have to run all models on these datasets again. Luckily they are quite small.

Rerunning the existing script should automatically do this (preferring to use STS.v2 over STS as superseded datasets are filtered by default).
