### ISSUE TITLE
Add embeddings speed

### ISSUE THREAD

**Issue by vprelovac** [embeddings-benchmark/mteb#108]
An important factor in choosing embeddings is the speed of embedding.

I suggest adding a "tab" in the evluation called "Speed" and it would be represented in sentences/sec for example (canalso be tokens/sec). 

This is a very useful feature of the SBERT site for example:
https://www.sbert.net/docs/pretrained-models/msmarco-v3.html

and efficiency as a parameter is already mentioned in your paper.

**Comment by Muennighoff** [comment]
It's a great point - unfortunately, since the evaluation is not automatic but each user evaluates individually, it's hard to compare speeds as users may use different CPUs / GPUs / environments.
E.g. it's also very hard to fairly compare speed with the APIs, since you cannot run them locally at all.

If you have a good idea for solving this, would love to add it to the leaderboard, but the best I can think of is doing it manually for each model.

**Comment by vprelovac** [comment]
Oh I see. Well the solution is obviously to make the evaluation automatic. We can donate a GPU to run evaluations (24/7) if you want to make an automated script.

**Comment by KennethEnevoldsen** [comment]
Note that we have implemented two speed tasks #848 - they simply need to be run on comparable hardware.

**Comment by KennethEnevoldsen** [comment]
We have in the most recent leaderboard ([demo here](https://huggingface.co/spaces/mteb/leaderboard_2_demo) and expected release in Jan) added this plot, which I believe generally related to embedding speed (though of course not entirely):

<img width="843" alt="Screenshot 2024-12-29 at 17 21 13" src="https://github.com/user-attachments/assets/1c9180e2-a66d-475c-b272-fab087fe29f6" />
