### ISSUE TITLE
Issue with Language Classification Task for Swahili in MTEB

### ISSUE THREAD

**Issue by msamwelmollel** [embeddings-benchmark/mteb#1086]
Dear MTEB,

I am writing to report an issue I encountered while evaluating the "LanguageClassification" task, which I know supports Swahili. When I tried to add "swa" as the language for this task, it resulted in an error.

Below is my current evaluation code. The evaluation works correctly if I comment on the "LanguageClassification" task.

pip install mteb
pip install sentence-transformers
import mteb
from sentence_transformers import SentenceTransformer
import torch

model_name = "MultiLinguSwahili-serengeti-E250-nli-matryoshka"    
publisher = "sartifyllc"

models = ["sartifyllc/MultiLinguSwahili-bert-base-sw-cased-nli-matryoshka", f"{publisher}/{model_name}"]

for model_name in models:
    truncate_dim = 768
    language = "swa"

    device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")
    model = SentenceTransformer(model_name, device=device, trust_remote_code=True)

    tasks = [
        mteb.get_task("AfriSentiClassification", languages=["swa"]),
        mteb.get_task("AfriSentiLangClassification", languages=["swa"]),
        mteb.get_task("MasakhaNEWSClassification", languages=["swa"]),
        mteb.get_task("MassiveIntentClassification", languages=["swa"]),
        mteb.get_task("MassiveScenarioClassification", languages=["swa"]),
        mteb.get_task("SwahiliNewsClassification", languages=["swa"]),
        mteb.get_task("LanguageClassification", languages=["swa"]),  # if I comment it works
    ]

    evaluation = mteb.MTEB(tasks=tasks)
    results = evaluation.run(model, output_folder=f"{model_name}")

    tasks = mteb.get_tasks(task_types=["PairClassification", "Reranking", "BitextMining", "Clustering", "Retrieval"], languages=["swa"])

    evaluation = mteb.MTEB(tasks=tasks)
    results = evaluation.run(model, output_folder=f"{model_name}")
    
The error occurs specifically when trying to include the "LanguageClassification" task with Swahili ("swa") as the language. I would appreciate it if you could look into this issue.

Thank you so much for the platform.

Regards,

Michael

**Comment by asparius** [comment]
The issue stems from the fact that language classification does not comply with language encodings preferred in MMTEB. You should be fine with using sw instead of swa as in the [source file](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Classification/multilingual/LanguageClassification.py). I am creating PR to resolve this issue.

**Comment by KennethEnevoldsen** [comment]
@msamwelmollel thanks for the issue.

However, for future reference, it is nice to have a minimal reproducible example:

```
import mteb

tasks = mteb.get_tasks(tasks=["LanguageClassification"], languages=["swa"])

model = mteb.get_model("sentence-transformers/all-MiniLM-L6-v2")
eval = mteb.MTEB(tasks=tasks)
eval.run(model, overwrite_results=True)
```

This does indeed result in an error. Which as @asparius says is due to the language code being incorrectly formatted. I have made a fix (@asparius sadly the fix you proposed did not resolve the issue).

Do note that:

```
tasks = mteb.get_tasks(tasks=["LanguageClassification"], languages=["swa"])
# and
tasks = mteb.get_tasks(tasks=["LanguageClassification"])
```

results in the same task. This is intended. Since Language classification is about determining the language. So as long as "swa" is contained within the dataset it should be equivalent. Let me know if you expected any other behaviour. 


---

Then a few minor comments. You can simplify the following

```diff
-tasks = [
-    mteb.get_task("AfriSentiClassification", languages=["swa"]),
-    mteb.get_task("AfriSentiLangClassification", languages=["swa"]),
-    mteb.get_task("MasakhaNEWSClassification", languages=["swa"]),
-    mteb.get_task("MassiveIntentClassification", languages=["swa"]),
-    mteb.get_task("MassiveScenarioClassification", languages=["swa"]),
-    mteb.get_task("SwahiliNewsClassification", languages=["swa"]),
-    mteb.get_task("LanguageClassification", languages=["swa"]),  # if I comment it works
-]
tasks = mteb.get_tasks(tasks = [
     "AfriSentiClassification"‚ 
     "AfriSentiLangClassification", 
     "MasakhaNEWSClassification", )
     "MassiveIntentClassification", # note this is a translated dataset and might not be a ideal to evaluate on
     "MassiveScenarioClassification", # same for this one
     "SwahiliNewsClassification",
     "LanguageClassification"
     ], languages = ["swa"])
```
