### ISSUE TITLE
Cannot reproduce exact numbers (MTEB French retrieval) from the leaderboard

### ISSUE THREAD

**Issue by PxYu** [embeddings-benchmark/mteb#1314]
Hi there,

I am trying to verify if the numbers on the MTEB French retrieval leaderboard can be reproduced, using mGTE as an example. I am getting lower numbers on 2/5 datasets. Here is my code:

```
import mteb
from sentence_transformers import SentenceTransformer

model_name_or_path="Alibaba-NLP/gte-multilingual-base"
model = SentenceTransformer(model_name_or_path, trust_remote_code=True)

tasks = mteb.get_tasks(
    tasks=["AlloprofRetrieval", "BSARDRetrieval", "MintakaRetrieval", "SyntecRetrieval", "XPQARetrieval"], 
    languages=["fra"],
    eval_splits=['test'],
    task_types=["retrieval"]
)

evaluation = mteb.MTEB(tasks=tasks)
results = evaluation.run(
    model,
    output_folder=f"results/{model_name_or_path}",
    encode_kwargs = {'batch_size': 8}
)

for r in results:
    print(r.task_name, r.scores['test'][0]['ndcg_at_10'], "\n")
```

Results I get:

AlloprofRetrieval 0.49213

BSARDRetrieval 0.19224

MintakaRetrieval 0.34703

SyntecRetrieval 0.83043

XPQARetrieval 0.67386

However, the nDCG@10 reported on AlloprofRetrieval and BSARDRetrieval are 53.64 and 26.11.

Can someone help clarify the issue here? Thank you!

**Comment by Samoed** [comment]
I ran `Lajavaness/bilingual-embedding-small` and got the same results as on the leaderboard. I'll try to check `gte-multilingual-base`.

**Comment by Samoed** [comment]
I obtained results similar to yours, but it's difficult to determine what's off with the self-reported results.

[gte-multilingual-base.zip](https://github.com/user-attachments/files/17497628/gte-multilingual-base.zip)

**Comment by PxYu** [comment]
Thanks for confirming, @Samoed . For context, I wanted to evaluate my own multilingual model against the models on the leaderboard. However, it's a bit frustrating that the numbers up there can't be directly compared since they cannot be reproduced, which somewhat defeats the purpose of the leaderboard, doesn't it?

**Comment by isaac-chung** [comment]
Tagging @imenelydiaker in case a 2nd pair of eyes might help.

**Comment by imenelydiaker** [comment]
Hi,

We have done an update on some datasets in the latest version of [our paper](https://arxiv.org/abs/2405.20468v2) (due to a reviewing process, update will come soon), with these changes results for `SyntecRetrieval` are higher for all models. **BUT, we haven't updated the tasks and datasets on mteb**. So the benchmark uses the same datasets we used in [the first version of the paper](https://arxiv.org/abs/2405.20468v1).

Since the results are self-reported (authors fill a README.md file in their model's repository), it can be due to a human error or anything else. I suggest you ask the model's authors directly which version of the datasets they used in their evaluation (they have the information in results json files). 

For BSARD, it should be: `5effa1b9b5fa3b0f9e12523e6e43e5f86a6e6d59`
For SyntecRetrieval: `19661ccdca4dfc2d15122d776b61685f48c68ca9`

**Comment by isaac-chung** [comment]
Closing this now.
