### ISSUE TITLE
Leaderboard 2.0: Re-add model searchbar from 1.0

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#1347]
Currently, there is no way to search for specific models in the leaderboard. Re-adding the search functionality from v1 would be a great addition

**Comment by x-tabdeveloping** [comment]
will do

**Comment by x-tabdeveloping** [comment]
Hey! So I've been looking into this. Just out of curiosity, can someone explain a couple of things about the original search bar's functionality?

Is it correctly understood that there is an **OR** relationship between queries?
And if so, do you think I should implement this the same way?
Since `str.contains()` is already Regex sensitive, couldn't we just leave it as is, and let users use Regex to handle more complex queries?
```python
if search_query:
            names = df["Model"].map(lambda x: re.match("<a .+?>(.+)</a>", x).group(1))
            masks = []
            for query in search_query.split(";"):
                masks.append(names.str.lower().str.contains(query.lower()))
            df = df[reduce(lambda a, b: a | b, masks)]
```

I'm just gonna tag you guys, cause you worked on the OG leaderboard (@orionw, @Muennighoff )

**Comment by orionw** [comment]
I wasn’t part of the original design so can’t answer fully, but my guess is that it’s just an artifact.

I think using a regex is a great idea and is more expressive!

**Comment by Muennighoff** [comment]
cc @tomaarsen who designed the search bar IIRC

**Comment by tomaarsen** [comment]
> Is it correctly understood that there is an OR relationship between queries?

Yeah, that was my original design - that way you can filter for a few models of interest. Regex is also quite useful to have, I like it.
