### ISSUE TITLE
Leaderboard: Add an Overview leaderboard

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#1432]
Instead of having either English or Multilingual as the default why not have "overview" as the default?

Something like:

 | Model Name | Multilingual | English | LongEmbed | ... |
 | --- | ---  | --- | --- | --- |
| M1 | ...  |  |   |   |
| M2 |   |  |   |   |

(this does not need to be added for the first version of the benchmark)

**Comment by isaac-chung** [comment]
That's an interesting idea! When we think of a leaderboard, we think of rankings. Would this be sort of a "meta" leaderboard, where the models have a rank based on all the benchmarks, e.g. a borda count over all benchmarks? Or based on one of multilingual or English?

If it's the former, one probable scenario I'm not sure how to deal with is with missing values, i.e.  if that model does not have values for a particular benchmark(s). 

Otherwise, we could enable sorting models based on each benchmark available. And users can click into each benchmark's breakdown.
