### ISSUE TITLE
 We should be able to filter GGUF models

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#1579]
> We should be able to filter GGUF models, since they are compatible with llama.cpp

Originally posted here: https://huggingface.co/spaces/mteb/leaderboard/discussions/146

**Comment by KennethEnevoldsen** [comment]
Thanks for the suggestion MMalucelli.

We are currently developing a new and improved leaderboard - close to ready; you can see the demo [here](https://huggingface.co/spaces/mteb/leaderboard_2_demo), it still has some issues we have to resolve.

However, one of the things we are improving from the previous leaderboard is that we remove duplicates e.g. [this](https://huggingface.co/KeyurRamoliya/multilingual-e5-large-instruct-GGUF) would be a duplicate of [e5-multilingual-instruct](https://huggingface.co/intfloat/multilingual-e5-large-instruct).

As far as I can see from popular models, these aren't co-hosted in the same repository as e.g. ONNX is ([example](https://huggingface.co/intfloat/multilingual-e5-large-instruct/tree/main/onnx)).

Let me know if you have a suggestion for this

**Comment by MMalucelli** [comment]
It's hard to even filter clearly the embedding models on HuggingFace, let alone filter which are GGUF. The leaderboard is really the best alternative. Just thought it would be helpful since you could run them on Ollama. I mean, you can always quantize the original model yourself as well, but different techniques result in different performances, anyway...

Since you mentioned:

HuggingFace has model trees, which helps tracking where the model is derived from.

The leaderboard could contain basically all benchmarked models, with the option to filter by the original models (could be the default).

> However, one of the things we are improving from the previous leaderboard is that we remove duplicates e.g. [this](https://huggingface.co/KeyurRamoliya/multilingual-e5-large-instruct-GGUF) would be a duplicate of [e5-multilingual-instruct](https://huggingface.co/intfloat/multilingual-e5-large-instruct).

The [GGUF mode](https://huggingface.co/KeyurRamoliya/multilingual-e5-large-instruct-GGUF)l is actually a Q8 version of the model. If it goes through the same benchmarks, we'd be able to compare the performance from the quantized model (which should use a little over half the memory of the original 16F in this example), with the full version.

In the current leaderboard, there's the memory usage estimate from fp32, but we have the tensor types information from each model, as well as the size of the repo. Couldn't this information be used for a better estimate?

Last but not least, a code benchmark addition would be fantastic (look [here](https://blog.voyageai.com/2024/12/04/voyage-code-3/)).

I'd be happy to help.

**Comment by KennethEnevoldsen** [comment]
Well if we were to include quantization we would have to figure out #1211. if you have the time I would be very happy to do a review. 

> Last but not least, a code benchmark addition would be fantastic (look [here](https://blog.voyageai.com/2024/12/04/voyage-code-3/)).

We be added in the next version leaderboard and is already available within the package. On the current leaderboard you can also find CoIR

**Comment by MMalucelli** [comment]
> Well if we were to include quantization we would have to figure out #1211. if you have the time I would be very happy to do a review.

I took a look at the issue and I haven't figured where exactly does the issue lie. I had some thoughts on it, I tried writing what came to mind but it can be BS.

There could be a separation between base models (like an "official" leaderboard) and every run ("unofficial" or "general"), with some moderation in the "every" part since we don't want to be looking at, e.g., 8 equal Q5_K_M gte-Qwen2.5s sequentially. 

Maybe the user submits the experimental run for approval, with structured parameter specifications? As long as the official lb is kept clean, I think there's room for testing the moderation approach for the unofficial one. The unofficial should also have the official one's performances, for peer comparison.

Besides, testing with code specific parameters and running the code benchmarks could help my use case.

> We be added in the next version leaderboard and is already available within the package. On the current leaderboard you can also find CoIR

CoIR, unfortunately, doesn't seem to be tested often, but thank you for pointing it out.

I mentioned [this](https://github.com/user-attachments/assets/35d5e5b3-c519-4bf5-9dea-7456776df6b9) but I'm not really sure if it can be leveraged.

What I really do think is that the quantized models are different from the base models. Whether the quantization was done with an imatrix and which file was used also influences the performance.

And I meant earlier that models that are tagged with GGUF should be able to be filtered in the leaderboard, the tag is already available. Like a format tab. Embedding models are more viable locally, since they tend to be smaller. 

The leaderboard is kind of double edged, users will be mostly searching for efficiency, while the model developers will be looking to show what they are capable of.

**Comment by KennethEnevoldsen** [comment]
> I mentioned [this](https://github.com/user-attachments/assets/35d5e5b3-c519-4bf5-9dea-7456776df6b9) but I'm not really sure if it can be leveraged.

This is not currently public (we would be more than happy to implement it if it were)

> The leaderboard is kind of double edged, users will be mostly searching for efficiency, while the model developers will be looking to show what they are capable of.

We are working on this in the v2 of the benchmark, which e.g. include:

<img width="831" alt="Screenshot 2024-12-22 at 22 32 45" src="https://github.com/user-attachments/assets/f01a7a71-6bfa-4f65-9960-6373b2b919ae" />

For now I will close this PR in favor of #1622 which partly solved it by using the tags, but does not search the tree of derivatives. This might encourage more developers to specifically add the GGUF model.
