### ISSUE TITLE
MindSmallReranking dataset does not exist anymore on Huggingface Hub

### ISSUE THREAD

**Issue by anihm136** [embeddings-benchmark/mteb#301]
The dataset for MindSmallReranking (supposed to be at https://huggingface.co/datasets/msnews/mind-small-reranking) does not appear to exist anymore on the hub. Is there an alternative for this? For instance, I found this - https://huggingface.co/datasets/mteb/mind_small, not sure if this is the intended dataset for this task

**Comment by imenelydiaker** [comment]
Hello,

The original evaluation was done on the `mteb/mind_small` dataset (datasets are copied by mteb to make sure they will always be available in case the original one is deleted, just as this case). 

There have been an update recently that changed the source of the dataset in the package, we will fix this. You can use the mteb version of the dataset meanwhile (although it would be nice to check why the original dataset was removed from HF).

@MartinBernstorff I see that the metadata of the [MindSmallReranking task](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Reranking/en/MindSmallReranking.py) have been updated, is it possible to put back the `mteb/mind_small` in hf_hub_name ?

**Comment by KennethEnevoldsen** [comment]
@imenelydiaker I have added a fix in #303, always feel free to just do these as well.

Datasets getting removed can be quite problematic for (M)MTEB, we might consider a solution where we use keep both the original dataset and always upload a version to MTEB as well. Something like:

If a "mteb" version of the dataset exist use that, otherwise use the original version. It should then also be possible to "update" the mteb version from the original if desired.
