### ISSUE TITLE
To speed up MindSmallReranking

### ISSUE THREAD

**Issue by memray** [embeddings-benchmark/mteb#738]
Hi there,

It is observed that MindSmallReranking is extremely slow (also mentioned in https://github.com/embeddings-benchmark/mteb/issues/381). 

I checked the data and found there is a waste in encoding. There are 70,938 records and 5M sentences in the dataset, but it turns out most of them are duplicate. Simple dedup can save 100x time for encoding (not sure if this issue applies to other datasets).

#sample = 5,020,605
#dedup(query)+dedup(pos)+dedup(neg) = 44,577
#dedup(all) = 41,803

<img width="842" alt="image" src="https://github.com/embeddings-benchmark/mteb/assets/4197249/52cbb531-b480-4eed-ad0a-ce5fe5e3b0b6">

**Comment by imenelydiaker** [comment]
That's really nice! Cool to have found a way of going faster without having to subsample the dataset.

I think it's duplicated because of the dataset formatting expectations for the MTEB reranking task.

It would be better to have IDs for queries, positive and negative elements. This would allow encoding the same text only once even if it is used multiple times. It may require a vector database and a big refactoring of reranking tasks, so I'm not very sure about how we should handle this.

**Comment by w601sxs** [comment]
currently MindSmallReranking errors out - 


https://huggingface.co/spaces/mteb/leaderboard/discussions/114

**Comment by AlexeyVatolin** [comment]
The work here is done, I think. The computation time of this benchmark decreased by more then 800 seconds on the `paraphrase-multilingual-MiniLM-L12-v2` model

**Comment by imenelydiaker** [comment]
Amazing! Thank you @AlexeyVatolin, will close this issue 🙂
