### ISSUE TITLE
Add a Speed task

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#848]
Add system descriptors to results file to e.g. estimate get an idea about the runtime (e.g. when examining evaluation speed or debugging).

potentially a function somewhat like:
```
    def get_system_info(self) -> dict[str, str]:
        """
        Returns a dictionary with system information.
        """
        info = {}
        info["platform"] = platform.system()
        info["platform-release"] = platform.release()
        info["platform-version"] = platform.version()
        info["architecture"] = platform.machine()
        info["processor"] = platform.processor()
        info["ram"] = str(round(psutil.virtual_memory().total / (1024.0**3))) + " GB"
        info["Physical cores"] = psutil.cpu_count(logical=False)
        info["Total cores"] = psutil.cpu_count(logical=True)
        return info
```

Potentially, with some GPU stuff added as well.

An alternative would be to add "speed" as a task e.g. as seen in the [scandinavian embedding benchmark](https://github.com/KennethEnevoldsen/scandinavian-embedding-benchmark/blob/c8376f967d1294419be1d3eb41217d04cd3a65d3/src/seb/registered_tasks/speed.py#L83-L96)

**Comment by isaac-chung** [comment]
Seems like an evolution from https://github.com/embeddings-benchmark/mteb/issues/64.

Instead of expanding `MTEBResults`, I'm leaning towards adding "speed" as a task. There we can report CPU time / GPU time depending on what's available. This would really only be different per model (on a fixed dataset) so it seems more meaningful to be framed as a separate task. Could potentially be a column on the LB too?

Tagging @Muennighoff @imenelydiaker as well.

**Comment by KennethEnevoldsen** [comment]
Yes probably better. Would it even be possible to record other things like memory usage, gpu-usage etc.

**Comment by isaac-chung** [comment]
Potentially, this `SpeedTask` can inherit from `AbsTask`. The `load_data()` method could directly read `"the_ugly_duckling.txt"` (love this btw). 

For the `GPUTask`, GPU info/usage can be recorded as a list like [here](https://thepythoncode.com/article/get-hardware-system-information-python#GPU_info).
