### ISSUE TITLE
LongEmbed main score

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#868]
The main score for LEMBPasskeyRetrieval is set to `ndcg_at_10` but in the [paper](https://arxiv.org/pdf/2404.12096v2) you don't use that as your main score for passkey, no? @dwzhu-pku 

https://github.com/embeddings-benchmark/mteb/blob/fe912bc2d676772ce059522639bcd14e9c80ecb2/mteb/tasks/Retrieval/eng/LEMBPasskeyRetrieval.py#L33C21-L33C31

**Comment by dwzhu-pku** [comment]
Yes, it should be `ndcg_at_1`, thanks for your correction. I hadn't noticed this error before, because I didn't find the usage of the `main_score` parameter. Now I realize it is meant to be used in the leaderboard. The same modification is needed for LEMBNeedleRetrieval as well. Do I need to open a PR or you could simply fix this for me? :-) @Muennighoff

**Comment by Muennighoff** [comment]
Sure can you review? :) https://github.com/embeddings-benchmark/mteb/pull/869

**Comment by KennethEnevoldsen** [comment]
Merged in -- thanks!

@dwzhu-pku, we should probably also add longEmbed to mteb/benchmarks.py
